# Generated by Django 4.2.4 on 2023-08-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=63)),
                ("slug", models.SlugField(max_length=63, unique=True)),
                ("text", models.TextField()),
                ("pub_date", models.DateField()),
                ("startups", models.ManyToManyField(to="organizer.startup")),
                ("tags", models.ManyToManyField(to="organizer.tag")),
            ],
        ),
    ]
