# Generated by Django 4.2.4 on 2023-08-19 14:41

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0003_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=63,
                populate_from=["name"],
                unique=True,
            ),
        ),
    ]
